src/Application/UkrLogic/MainBundle/Entity/Post.php
<?php

namespace Application\UkrLogic\MainBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * Post
 */
class Post
{
    /**
     * @var integer
     */
    private $id;


    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @var string
     */
    private $title;

    /**
     * @var string
     */
    private $content;

    /**
     * @var \DateTime
     */
    private $date;

    /**
     * @var boolean
     */
    private $active;

    /**
     * @var string
     */
    private $image;

    /**
     * @var string
     */
    private $metaTitle;

    /**
     * @var string
     */
    private $metaDescription;

    /**
     * @var string
     */
    private $metaKeywords;

    /**
     * Set title
     *
     * @param string $title
     * @return Post
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Get title
     *
     * @return string 
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set content
     *
     * @param string $content
     * @return Post
     */
    public function setContent($content)
    {
        $this->content = $content;

        return $this;
    }

    /**
     * Get content
     *
     * @return string 
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * Set date
     *
     * @param \DateTime $date
     * @return Post
     */
    public function setDate($date)
    {
        $this->date = $date;

        return $this;
    }

    /**
     * Get date
     *
     * @return \DateTime 
     */
    public function getDate()
    {
        return $this->date;
    }

    /**
     * Set active
     *
     * @param boolean $active
     * @return Post
     */
    public function setActive($active)
    {
        $this->active = $active;

        return $this;
    }

    /**
     * Get active
     *
     * @return boolean 
     */
    public function getActive()
    {
        return $this->active;
    }

    /**
     * Set image
     *
     * @param string $image
     * @return Post
     */
    public function setImage($image)
    {
        $this->image = $image;

        return $this;
    }

    /**
     * Get image
     *
     * @return string 
     */
    public function getImage()
    {
        return $this->image;
    }

    /**
     * Set metaTitle
     *
     * @param string $metaTitle
     * @return Post
     */
    public function setMetaTitle($metaTitle)
    {
        $this->metaTitle = $metaTitle;

        return $this;
    }

    /**
     * Get metaTitle
     *
     * @return string 
     */
    public function getMetaTitle()
    {
        return $this->metaTitle;
    }

    /**
     * Set metaDescription
     *
     * @param string $metaDescription
     * @return Post
     */
    public function setMetaDescription($metaDescription)
    {
        $this->metaDescription = $metaDescription;

        return $this;
    }

    /**
     * Get metaDescription
     *
     * @return string 
     */
    public function getMetaDescription()
    {
        return $this->metaDescription;
    }

    /**
     * Set metaKeywords
     *
     * @param string $metaKeywords
     * @return Post
     */
    public function setMetaKeywords($metaKeywords)
    {
        $this->metaKeywords = $metaKeywords;

        return $this;
    }


    /**
     * @Assert\File(maxSize="6000000")
     */
    private $file;

    /**
     * Sets file.
     *
     * @param UploadedFile $file
     */
    public function setFile(UploadedFile $file = null)
    {
        $this->file = $file;
    }

    /**
     * Get file.
     *
     * @return UploadedFile
     */
    public function getFile()
    {
        return $this->file;
    }

    /**
     * Get metaKeywords
     *
     * @return string 
     */
    public function getMetaKeywords()
    {
        return $this->metaKeywords;
    }
    public function getAbsolutePath()
    {
        return null === $this->image
            ? null
            : $this->getUploadRootDir().'/'.$this->image;
    }

    public function getWebPath()
    {
        return null === $this->image
            ? null
            : $this->getUploadDir().'/'.$this->image;
    }

    protected function getUploadRootDir()
    {
        return __DIR__.'/../../../../../web/'.$this->getUploadDir();
    }

    protected function getUploadDir()
    {
        return '/uploads/post';
    }

    public function upload()
    {
        if (null === $this->getFile()) {
            return;
        }

        $this->image = sprintf("%d_%s", $this->getId(), $this->getFile()->getClientOriginalName());

        $this->getFile()->move($this->getUploadRootDir(), $this->image);
        $this->file = null;
    }

    public function __construct()
    {
        $this->setDate(new \DateTime());
    }
}

src/Application/UkrLogic/MainBundle/Form/CommentType.php
<?php

namespace Application\UkrLogic\MainBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;
use Symfony\Component\Security\Core\SecurityContext;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * Class CommentType
 * @package Application\UkrLogic\MainBundle\Form
 */
class CommentType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('text', 'textarea', ['label' => false, 'attr' => ['placeholder' => 'Введите отзыв']])
            ->add('submit', 'submit', ['label' => 'Ок']);
    }

    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Application\UkrLogic\MainBundle\Entity\Comment'
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'application_ukrlogic_mainbundle_comment';
    }
}

src/Application/UkrLogic/MainBundle/Resources/views/Page/about.html.twig
{% extends "@ApplicationUkrLogicMain/layout-main.html.twig" %}


{% block content %}
<div class="content">
    <img style="margin: 0 25% 0 25%; width: 50%;" src="{{ asset("img/logoo.jpg") }}">

    <div class="content-blue clearfix" id="feedback-content">

        <p>
            <strong style="color: black;">
                Туристическая фирма Color Travel, готова организовать Ваш отдых или путешествие от А до Я.
                Уникальная программа поиска туров, позволяет менеджерам туристического отдела за считаные минуты
                подобрать горящий или заранее запланированный тур по наиболее интересной цене.
                Наши партнеры это лидеры тиристической индустрии - поэтому Вы можете быть уверенны, что спектр
                предлагаемых нами услуг будет предоставлен на высшем уровне.
            </strong>
        </p>

        <img style="width: 100%;" src="{{ asset("img/post.jpg") }}">
        <div id="showmap" style="width: 100%;margin-top: -110px;z-index: 999;position: relative;">
			<a href="/app_dev.php/avia-tickets" style="float: left;width: 33%;">Просмотреть увеличенную карту</a>
			<a href="/app_dev.php/avia-tickets" style="float: left;width: 33%;">Просмотреть увеличенную карту</a>
			<a href="/app_dev.php/avia-tickets" style="float: left;width: 33%;">Просмотреть увеличенную карту</a>
		</div>
		<br>
		<img style="width: 100%;" src="{{ asset("img/post2.jpg") }}">

        <div class="content-blue clearfix" id="feedback-form">
            <h2>Обратная связь</h2>
            {{ form_start(form, { 'attr': { 'class': 'contact-form' } }) }}
            {{ form_errors(form.captcha) }}
            <div class="main-fields">
                <div class="half first">
                    {{ form_widget(form.name, { 'attr': {'placeholder': "Ф.И.О"} }) }}
                    {{ form_widget(form.email, {'attr': {'placeholder' : 'E-mail' } }) }}
                    {{ form_widget(form.phone, {'attr': {'placeholder' : 'Контактный телефон' } }) }}
                </div>
                <div class="half second">
                    {{ form_widget(form.captcha, { 'width': 120, 'height': 50 }) }}
                    {{ form_widget(form.submit, { 'label': 'Отправить' }) }}
                </div>
            </div>
            {{ form_widget(form.message, {'attr': {'placeholder' : 'Введите ваше сообщение...' } }) }}
            {{ form_end(form) }}
        </div>
    </div>
    {% endblock %}

    {% form_theme form _self %}

    {% block captcha_widget %}
    {% spaceless %}
        <div class="captcha">
            <img src="{{ captcha_code }}" title="captcha" width="{{ captcha_width }}"
                 height="{{ captcha_height }}"/>
        </div>
        {{ form_widget(form, { 'attr': { 'placeholder': "Введите код с изображения" } }) }}
    {% endspaceless %}
{% endblock %}

src/Application/UkrLogic/MainBundle/Resources/views/Page/index.html.twig
{% extends "@ApplicationUkrLogicMain/layout-main.html.twig" %}

{% block title %}{{ page.metaTitle }}{% endblock %}
{% block meta_keywords %}{{ page.metaKeywords }}{% endblock %}
{% block meta_description %}{{ page.metaDescription }}{% endblock %}
{% block content %}
        {{ include(template_from_string(page.content)) | raw }}
{% endblock %}

src/Application/UkrLogic/MainBundle/Resources/views/Page/post.html.twig
{% extends "@ApplicationUkrLogicMain/layout-main.html.twig" %}

{% block title %}{{ post.metaTitle }}{% endblock %}
{% block meta_keywords %}{{ post.metaKeywords }}{% endblock %}
{% block meta_description %}{{ post.metaDescription }}{% endblock %}
{% block content %}
    <div id="post">
        <h2 id="post-title">{{ post.title }}</h2>
        <div id="post-date">{{ post.date.format('Y-m-d') }}</div>

        {% if post.webPath %}
            <div id="main-post-image">
                <img src="{{ post.webPath }}" alt="{{ post.title }}"/>
            </div>
        {% endif %}

        <div id="post-content">{{ include(template_from_string(post.content)) | raw }}</div>
    </div>
{% endblock %}